### ISSUE TITLE
Simulation_Activity.py doesn't work automatically when following the guide lines

### ISSUE THREAD

**Issue by ThijsLedeboer** [mbafrani/AutomaticProcessSimulation#15]
Hi, 

First of all nice paper and very useful. However, one remark by default when downloading the code you have to modify line 106 and 107 of simulation_activity.py. By default, it tries to read "Prozessmodel.xes" and not the file path you give in the command line. 
![image](https://user-images.githubusercontent.com/65283284/118612643-46893b00-b7be-11eb-8d2e-a1589edbb62d.png)

**Comment by mbafrani** [comment]
Hi,

Thanks for the hint, it's fixed now. We are in the middle of the debugging due to the current update of the pm4py library and that was the reason.
